// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YmmcContainerTrackerApi.Data;

#nullable disable

namespace YmmcContainerTrackerApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251212162641_AddContainerAuditLogs")]
    partial class AddContainerAuditLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YmmcContainerTrackerApi.Models.ContainerAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ChangedFields")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ItemNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserRole")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("ItemNo");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Username");

                    b.ToTable("ContainerAuditLogs", "dbo");
                });

            modelBuilder.Entity("YmmcContainerTrackerApi.Models.ReturnableContainers", b =>
                {
                    b.Property<string>("ItemNo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Item_No");

                    b.Property<string>("AlternateId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Alternate_ID");

                    b.Property<decimal?>("CollapsedHeight")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Collapsed_Height");

                    b.Property<string>("ContainerNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Container_Number");

                    b.Property<decimal?>("OutsideHeight")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Outside_Height");

                    b.Property<decimal?>("OutsideLength")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Outside_Length");

                    b.Property<decimal?>("OutsideWidth")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Outside_Width");

                    b.Property<int?>("PackQuantity")
                        .HasColumnType("int")
                        .HasColumnName("Pack_Quantity");

                    b.Property<string>("PackingCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Packing_Code");

                    b.Property<string>("PrefixCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Prefix_Code");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Weight");

                    b.HasKey("ItemNo");

                    b.HasIndex("ItemNo")
                        .IsUnique();

                    b.ToTable("RtrnCotnr_Main", "RtrnCotnr");
                });

            modelBuilder.Entity("YmmcContainerTrackerApi.Models.ReturnableContainersStage", b =>
                {
                    b.Property<string>("AlternateId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Alternate_ID");

                    b.Property<string>("CollapsedHeight")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Collapsed_Height");

                    b.Property<string>("ContainerNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Container_Number");

                    b.Property<string>("ItemNo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Item_No");

                    b.Property<string>("OutsideHeight")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Outside_Height");

                    b.Property<string>("OutsideLength")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Outside_Length");

                    b.Property<string>("OutsideWidth")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Outside_Width");

                    b.Property<string>("PackQuantity")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Pack_Quantity");

                    b.Property<string>("PackingCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Packing_Code");

                    b.Property<string>("PrefixCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Prefix_Code");

                    b.Property<string>("Weight")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Weight");

                    b.ToTable("RtrnCotnr_Stage", "RtrnCotnr");
                });

            modelBuilder.Entity("YmmcContainerTrackerApi.Models.UserRole", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Username");

                    b.ToTable("UserRoles", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
